CREATE SCHEMA MEDICAL;

CREATE  TABLE "doctors_payments_dw_snowflake".MEDICAL.DIM_COMPANY ( 
	COMPANY_ID           INT NOT NULL   ,
	SUBMITTING_COMPANY_NAME VARCHAR(255)    ,
	COMPANY_MAKING_PMT_ID INT    ,
	COMPANY_MAKING_PMT_NAME VARCHAR(255)    ,
	COMPANY_MAKING_PMT_STATE VARCHAR(255)    ,
	COMPANY_MAKING_PMT_COUNTRY VARCHAR(255)    ,
	CONSTRAINT PK_DIM_COMPANY PRIMARY KEY ( COMPANY_ID )
 );

CREATE  TABLE "doctors_payments_dw_snowflake".MEDICAL.DIM_DATE ( 
	DATE_ID              INT NOT NULL   ,
	ORIGINAL_DATE        DATE    ,
	ISO_DATE             DATE    ,
	YEAR                 INT    ,
	QUARTER              INT    ,
	MONTH                INT    ,
	WEEK                 INT    ,
	DAY                  INT    ,
	MONTH_NAME           VARCHAR(100)    ,
	DAY_NAME             VARCHAR(100)    ,
	WEEK_OF_THE_YEAR     INT    ,
	DAY_OF_THE_YEAR      INT    ,
	CONSTRAINT PK_DIM_DATE PRIMARY KEY ( DATE_ID )
 );

CREATE  TABLE "doctors_payments_dw_snowflake".MEDICAL.DIM_PAYMENT_FORM ( 
	PAYMENT_FORM_ID      INT NOT NULL   ,
	PAYMENT_FORM         VARCHAR(255)    ,
	CONSTRAINT PK_DIM_PAYMENT_FORM PRIMARY KEY ( PAYMENT_FORM_ID )
 );

CREATE  TABLE "doctors_payments_dw_snowflake".MEDICAL.DIM_PAYMENT_NATURE ( 
	PAYMENT_NATURE_ID    INT NOT NULL   ,
	PAYMENT_NATURE_FORM  VARCHAR(255)    ,
	CONSTRAINT PK_DIM_PAYMENT_NATURE PRIMARY KEY ( PAYMENT_NATURE_ID )
 );

CREATE  TABLE "doctors_payments_dw_snowflake".MEDICAL.DIM_PAYMENT_TYPE ( 
	PAYMENT_TYPE_ID      INT NOT NULL   ,
	PAYMENT_TYPE         VARCHAR(100)    ,
	CONSTRAINT PK_DIM_PAYMENT_TYPE PRIMARY KEY ( PAYMENT_TYPE_ID )
 );

CREATE  TABLE "doctors_payments_dw_snowflake".MEDICAL.DIM_PRIMARY_TYPE ( 
	PRIMARY_TYPE_ID      INT NOT NULL   ,
	PRIMARY_TYPE         VARCHAR(255)    ,
	CONSTRAINT PK_DIM_PRIMARY_TYPE PRIMARY KEY ( PRIMARY_TYPE_ID )
 );

CREATE  TABLE "doctors_payments_dw_snowflake".MEDICAL.DIM_RECIPIENT ( 
	RECIPIENT_ID         INT NOT NULL   ,
	RECIPIENT_NPI        INT    ,
	RECIPIENT_ADDRESS_LINE_1 VARCHAR(100)    ,
	RECIPIENT_ADDRESS_LINE_2 VARCHAR(100)    ,
	RECIPIENT_CITY       VARCHAR(100)    ,
	RECIPIENT_STATE      VARCHAR(100)    ,
	RECIPIENT_ZIP_CODE   INT    ,
	RECIPIENT_COUNTRY    VARCHAR(100)    ,
	RECIPIENT_PROVINCE   VARCHAR(100)    ,
	RECIPIENT_POSTAL_CODE INT    ,
	CONSTRAINT PK_DIM_RECIPIENT PRIMARY KEY ( RECIPIENT_ID )
 );

CREATE  TABLE "doctors_payments_dw_snowflake".MEDICAL.DIM_SPECIALTY ( 
	SPECIALTY_ID         INT NOT NULL   ,
	SPECIALTY            VARCHAR(255)    ,
	CONSTRAINT PK_DIM_SPECIALTY PRIMARY KEY ( SPECIALTY_ID )
 );

CREATE  TABLE "doctors_payments_dw_snowflake".MEDICAL.FACTS_PAYMENTS ( 
	FACT_ID              INT NOT NULL   ,
	PMT_AMOUNT           DECIMAL(2)    ,
	NUMBER_OF_PAYMENTS   INT    ,
	POPULATION           INT    ,
	PAYMENT_TYPE_ID      INT    ,
	PAYMENT_FORM_ID      INT    ,
	PAYMENT_NATURE_ID    INT    ,
	DATE_ID              INT    ,
	COMPANY_ID           INT    ,
	RECIPIENT_ID         INT    ,
	SPECIALTY1_ID        INT    ,
	SPECIALTY2_ID        INT    ,
	SPECIALTY3_ID        INT    ,
	SPECIALTY4_ID        INT    ,
	SPECIALTY5_ID        INT    ,
	PRIMARY_TYPE1_ID     INT    ,
	PRIMARY_TYPE2_ID     INT    ,
	PRIMARY_TYPE3_ID     INT    ,
	PRIMARY_TYPE4_ID     INT    ,
	PRIMARY_TYPE5_ID     INT    ,
	PRINCIPAL_INVESTIGATOR1_ID INT    ,
	PRINCIPAL_INVESTIGATOR2_ID INT    ,
	PRINCIPAL_INVESTIGATOR3_ID INT    ,
	PRINCIPAL_INVESTIGATOR4_ID INT    ,
	PRINCIPAL_INVESTIGATOR5_ID INT    ,
	CONSTRAINT PK_PAYMENT_FACTS PRIMARY KEY ( FACT_ID )
 );

